model_list:
  - model_name: claude-sonnet-4-6
    litellm_params:
      model: openai/accounts/fireworks/models/kimi-k2p5
      api_base: https://api.fireworks.ai/inference/v1
      api_key: fw_7gHSHHxrTBXzJHxhPiSiWq
      drop_params: true
  - model_name: claude-sonnet-4-20250514
    litellm_params:
      model: openai/accounts/fireworks/models/kimi-k2p5
      api_base: https://api.fireworks.ai/inference/v1
      api_key: fw_7gHSHHxrTBXzJHxhPiSiWq
      drop_params: true
  - model_name: claude-sonnet-4-6-20250725
    litellm_params:
      model: openai/accounts/fireworks/models/kimi-k2p5
      api_base: https://api.fireworks.ai/inference/v1
      api_key: fw_7gHSHHxrTBXzJHxhPiSiWq
      drop_params: true
  - model_name: claude-opus-4-6-20250925
    litellm_params:
      model: openai/accounts/fireworks/models/kimi-k2p5
      api_base: https://api.fireworks.ai/inference/v1
      api_key: fw_7gHSHHxrTBXzJHxhPiSiWq
      drop_params: true
  - model_name: claude-opus-4-6
    litellm_params:
      model: openai/accounts/fireworks/models/kimi-k2p5
      api_base: https://api.fireworks.ai/inference/v1
      api_key: fw_7gHSHHxrTBXzJHxhPiSiWq
      drop_params: true
  - model_name: claude-haiku-4-5
    litellm_params:
      model: openai/accounts/fireworks/models/kimi-k2p5
      api_base: https://api.fireworks.ai/inference/v1
      api_key: fw_7gHSHHxrTBXzJHxhPiSiWq
      drop_params: true

litellm_settings:
  drop_params: true
  modify_params: true
  additional_drop_params:
    - output_config

general_settings:
  master_key: sk-litellm-proxy-key